return [[
local Matter = require(%s)

type ConnectionObject =
	{ Disconnect: () -> () }
	| { Destroy: () -> () }
	| { disconnect: () -> () }
	| { destroy: () -> () }
	| () -> ()

type CustomEvent =
	{ Connect: <T...>(T...) -> ConnectionObject }
	| { connect: <T...>(T...) -> ConnectionObject }
	| { on: <T...>(T...) -> ConnectionObject }

type Overrides = {
	component: <T>(name: string, defaultData: (T & {})?) -> Component<T>,
	log: (...any) -> (),
	useEvent: <T...>(
		instance: Instance | { [string]: CustomEvent } | CustomEvent,
		event: string | RBXScriptSignal<T...> | CustomEvent
	) -> () -> (number, T...),
	useHookState: <T>(
		discriminator: any?,
		cleanupCallback: (storage: T & {}) -> boolean
	) -> T & {},
	useThrottle: (seconds: number, discriminator: any?) -> boolean,
	Debugger: typeof(Matter.Debugger),
	None: typeof(Matter.None),
	Loop: typeof(Matter.Loop),
	World: World,
}

export type Component<T> = (initialData: T?) -> ComponentInstance<T>

-- TODO: Add below metatable to this when it works better
--export type ComponentInstance<T> = T

export type ComponentInstance<T> = typeof(setmetatable(
	{} :: {
		-- Luau does not support partial types, so we have to use any
		patch: (
			self: ComponentInstance<T>,
			changes: any
		) -> ComponentInstance<T>,
	},
	{} :: {
		__index: T,
	}
))

-- FUTURE: Improve above type and add this patch method when
-- typeof(setmetatable()) works better with generic args,
-- right now a recursive type such as this also seems
-- to break a lot of tooling such as luau-lsp
-- type ComponentInstanceMeta<T> = {
-- 	patch: (self: ComponentInstance<T>, changes: T) -> ComponentInstance<T>,
-- }

type SystemFn = (World, ...any) -> ()

type SystemTable = {
	system: SystemFn,
	event: string?,
	priority: number?,
	after: { System }?,
}

export type System = SystemFn | SystemTable

type WorldChangeRecord<T> = {
	old: ComponentInstance<T>?,
	new: ComponentInstance<T>?,
}

type WorldGetOrRemove =
	(<T>(self: World, id: number, Component<T>) -> ComponentInstance<T>)
	& (<T, U>(
		self: World,
		id: number,
		Component<T>,
		Component<U>
	) -> (ComponentInstance<T>, ComponentInstance<U>))
	& (<T, U, V>(
		self: World,
		id: number,
		Component<T>,
		Component<U>,
		Component<V>,
		...any
	) -> (ComponentInstance<T>, ComponentInstance<U>, ComponentInstance<V>))

type WorldQueryResult<T...> = typeof(setmetatable(
	{},
	{} :: {
		__iter: (self: WorldQueryResult<T...>) -> (() -> (number, T...)),
		__index: {
			without: (
				self: WorldQueryResult<T...>,
				...any
			) -> WorldQueryResult<T...>,
			snapshot: (self: WorldQueryResult<T...>) -> WorldQueryResult<T...>,
			next: (self: WorldQueryResult<T...>) -> (number, T...),
		},
	}
))

-- NOTE: We don't use more than 4 generics here since that
-- seems to currently lead to some performance issues
type WorldQuery =
	(<T>(self: World, Component<T>) -> WorldQueryResult<ComponentInstance<T>>)
	& (<T, U>(
		self: World,
		Component<T>,
		Component<U>
	) -> WorldQueryResult<ComponentInstance<T>, ComponentInstance<U>>)
	& (<T, U, V>(
		self: World,
		Component<T>,
		Component<U>,
		Component<V>
	) -> WorldQueryResult<
		ComponentInstance<T>,
		ComponentInstance<U>,
		ComponentInstance<V>
	>)
	& (<T, U, V, W>(
		self: World,
		Component<T>,
		Component<U>,
		Component<V>,
		Component<W>,
		...any
	) -> WorldQueryResult<
		ComponentInstance<T>,
		ComponentInstance<U>,
		ComponentInstance<V>,
		ComponentInstance<W>
	>)

type WorldQueryChanged = <T>(
	self: World,
	Component<T>
) -> (() -> (number, WorldChangeRecord<T>))

export type World = typeof(setmetatable(
	{},
	{} :: {
		__iter: (
			self: World
		) -> (() -> (number, { [any]: ComponentInstance<any> }), any),
		__index: {
			clear: (self: World) -> (),
			contains: (self: World, id: number) -> boolean,
			despawn: (self: World, id: number) -> (),
			get: WorldGetOrRemove,
			insert: (self: World, id: number, ...ComponentInstance<any>) -> (),
			optimizeQueries: (self: World) -> (),
			query: WorldQuery,
			queryChanged: WorldQueryChanged,
			remove: WorldGetOrRemove,
			replace: (self: World, id: number, ...ComponentInstance<any>) -> (),
			size: (self: World) -> number,
			spawn: (self: World, ...ComponentInstance<any>) -> number,
			spawnAt: (
				self: World,
				id: number,
				...ComponentInstance<any>
			) -> number,
			new: () -> World,
		},
	}
))

return (Matter :: any) :: Overrides
]]
